import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Noto_Serif_Telugu } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap',
  variable: '--font-roboto',
})

const notoSerifTelugu = Noto_Serif_Telugu({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-noto-serif-telugu',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='pt-br'>
      <body className={`${roboto.variable} ${notoSerifTelugu.variable}`}>
        {children}
      </body>
    </html>
  )
}
